### ISSUE TITLE
TODO, Improve behaviour

### ISSUE THREAD

**Issue by matipatapon** [matipatapon/BatteryMonitor#2]
It's stupid that it reads every 10 % always 90% 80% ... 10 % and surprise when you are unlucky

I think i will change it to start speak below 30% and inform about changes greater than  5%

When ? Maybe in the weekend

**Comment by michaelskyf** [comment]
I think that when battery level is below 5% it should start reporting it every 1%. I think it will "force" the user to plug their Steam Deck into the charger. Whaddya think?

**Comment by matipatapon** [comment]
I think it should warn user earlier ...
But it should probably be configurable in the config file to please everyone :P

**Comment by matipatapon** [comment]
I think BatteryMonitor should take list of battery levels for which it should read battery level

**Comment by matipatapon** [comment]
Fixed, thanks @michaelskyf  for help :smile:

**Comment by michaelskyf** [comment]
I didn't help lol
