### ISSUE TITLE
UwU

### ISSUE THREAD

**Issue by michaelskyf** [matipatapon/BatteryMonitor#5]
Add an option to uwu-fy the output text (including TTS).
Example:
Original: Battery level is 50%
After conversion: Battewy wevew is 50%

**Comment by matipatapon** [comment]
I don't have time for this project recently ... But I will come back to it soon :P
I think I will add it as another mode that you can set in config file

**Comment by michaelskyf** [comment]
Is there an UwU TTS? It would be great if the text was also spoken in uwu fashion!

**Comment by matipatapon** [comment]
The speech synthesizer hurts UwU speech ...
UwU -> U - W - U
